# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up Node.JS 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        npm ci
    - name: Mass create
      run: |
        pip3 install -r requirements.txt
        python3 massgethtml.py
    - name: Minify all pages
      run: npm run minify
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Sync all articles with the wiki"
